// generated by stringer -type UpdateEventTrigger; DO NOT EDIT

package owntracks

import "fmt"

const _UpdateEventTrigger_name = "PingEventCircularRegionEventBeaconRegionEventReportLocationResponseManualLocationUpdateTimerBasedUpdateAutoLocationUpdateUnknownTrigger"

var _UpdateEventTrigger_index = [...]uint8{0, 9, 28, 45, 67, 87, 103, 121, 135}

func (i UpdateEventTrigger) String() string {
	if i < 0 || i >= UpdateEventTrigger(len(_UpdateEventTrigger_index)-1) {
		return fmt.Sprintf("UpdateEventTrigger(%d)", i)
	}
	return _UpdateEventTrigger_name[_UpdateEventTrigger_index[i]:_UpdateEventTrigger_index[i+1]]
}
